Repository Project-MONAI/monai-deploy-informatics-gateway, pull requests merged in 2022-02, with the labels that each got.

#39 Update index.md
  README.md
  docs/index.md
Labels: documentation

#37 Implement message broker service with RabbitMQ as default provider
  guidelines/srs.md
  src/Api/LoggingDataDictionary.cs
  src/Api/MessageBroker/ExportCompleteMessage.cs
  src/Api/MessageBroker/ExportRequestMessage.cs
  src/Api/MessageBroker/IMessageBrokerPublisherService.cs
  src/Api/MessageBroker/IMessageBrokerSubscriberService.cs
  src/Api/MessageBroker/JsonMessage.cs
  src/Api/MessageBroker/Message.cs
  src/Api/MessageBroker/MessageReceivedEventArgs.cs
  src/Api/MessageBroker/WorkflowRequestMessage.cs
  src/Api/Storage/IStorageService.cs
  src/Api/Storage/Payload.cs
  src/Api/Test/LoggingDataDictionaryTest.cs
  src/Configuration/InformaticsGatewayConfiguration.cs
  src/Configuration/MessageBrokerConfiguration.cs
  src/Configuration/MessageBrokerRoutingKeysConfiguration.cs
  src/Configuration/ServiceCredentials.cs
  src/Configuration/StorageConfiguration.cs
  src/Database/Migrations/20220202191245_R1_Initialize.Designer.cs
  src/Database/Migrations/20220202191245_R1_Initialize.cs
  src/Database/Migrations/InformaticsGatewayContextModelSnapshot.cs
  src/InformaticsGateway/Monai.Deploy.InformaticsGateway.csproj
  src/InformaticsGateway/Program.cs
  src/InformaticsGateway/Repositories/InferenceRequestRepository.cs
  src/InformaticsGateway/Services/Connectors/DataRetrievalService.cs
  src/InformaticsGateway/Services/Connectors/PayloadAssembler.cs
  src/InformaticsGateway/Services/Connectors/PayloadNotificationService.cs
  src/InformaticsGateway/Services/Export/DicomWebExportService.cs
  src/InformaticsGateway/Services/Export/ExportServiceBase.cs
  src/InformaticsGateway/Services/Http/InferenceController.cs
  src/InformaticsGateway/Services/Scp/ScpServiceInternal.cs
  src/InformaticsGateway/Test/Services/Connectors/PayloadAssemblerTest.cs
  src/InformaticsGateway/Test/Services/Connectors/PayloadNotificationServiceTest.cs
  src/InformaticsGateway/Test/Services/Scp/PayloadTest.cs
  src/InformaticsGateway/appsettings.Development.json
  src/InformaticsGateway/appsettings.json
  src/MessageBroker/RabbitMq/ConfigurationKeys.cs
  src/MessageBroker/RabbitMq/Monai.Deploy.InformaticsGateway.MessageBroker.RabbitMq.csproj
  src/MessageBroker/RabbitMq/RabbitMqMessagePublisherService.cs
  src/MessageBroker/RabbitMq/RabbitMqMessageSubscriberService.cs
  src/Monai.Deploy.InformaticsGateway.sln
  src/Storage/MinIo/MinIoStorageService.cs
Labels: documentation, enhancement, design decisions

#45 README and doc updates
  README.md
  docs/index.md
Labels: documentation

#52 #42 Add release pipeline
  .github/.gitversion.yml
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/release.yml
  GitReleaseManager.yaml
  VERSION
  build.sh
  src/InformaticsGateway/Test/Services/Connectors/PayloadNotificationServiceTest.cs
  src/InformaticsGateway/Test/Services/Scp/PayloadTest.cs
  src/run-tests.sh
Labels: build

#53 Enable nuget cache on build workflow
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
Labels: build

#54 Prepare for 0.1.0 release
  .editorconfig
  .github/workflows/ci.yml
  CONTRIBUTING.md
  README.md
  codecov.yml
  docs/changelog.md
  docs/setup/setup.md
Labels: build
