Repository Project-MONAI/monai-deploy-informatics-gateway, pull requests merged in 2023-08, with the labels that each got.

#423 Requirements update to support offloading processing to third-party services
  guidelines/diagrams/mig-export.png
  guidelines/diagrams/mig-export.txt
  guidelines/diagrams/mig-scp.png
  guidelines/diagrams/mig-scp.txt
  guidelines/diagrams/mig.png
  guidelines/mig-sadd.md
  guidelines/mig-srs.md
Labels: documentation

#436 gh-435 Fix CLI to read log dir path from NLog config file
  docs/changelog.md
  src/CLI/Logging/Log.cs
  src/CLI/Monai.Deploy.InformaticsGateway.CLI.csproj
  src/CLI/Options/Common.cs
  src/CLI/Program.cs
  src/CLI/Properties/launchSettings.json
  src/CLI/Services/ConfigurationOptionAccessor.cs
  src/CLI/Services/ConfigurationService.cs
  src/CLI/Services/DockerRunner.cs
  src/CLI/Services/EmbeddedResource.cs
  src/CLI/Services/IConfigurationService.cs
  src/CLI/Services/NLogConfigurationOptionAccessor.cs
  src/CLI/Test/ConfigurationOptionAccessorTest.cs
  src/CLI/Test/ConfigurationServiceTest.cs
  src/CLI/Test/DockerRunnerTest.cs
  src/CLI/Test/NLogConfigurationOptionAccessorTest.cs
  src/CLI/Test/ProgramTest.cs
Labels: bug

#437 New APIs to get a list of input/output data plug-ins
  docs/api/rest/config.md
  docs/docfx.json
  docs/index.md
  docs/setup/cli.md
  docs/setup/setup.md
  src/Api/PluginNameAttribute.cs
  src/Api/Storage/DicomFileStorageMetadata.cs
  src/Api/Storage/FhirFileStorageMetadata.cs
  src/CLI/Commands/AetCommand.cs
  src/CLI/Commands/DestinationCommand.cs
  src/CLI/ExitCodes.cs
  src/CLI/Logging/Log.cs
  src/CLI/Test/AetCommandTest.cs
  src/CLI/Test/DestinationCommandTest.cs
  src/Client/Services/AeTitle{T}Service.cs
  src/Client/Test/AeTitleServiceTest.cs
  src/Configuration/DicomWebConfiguration.cs
  src/Configuration/ScuConfiguration.cs
  src/InformaticsGateway/Common/TypeExtensions.cs
  src/InformaticsGateway/Logging/Log.5000.DataPlugins.cs
  src/InformaticsGateway/Logging/Log.8000.HttpServices.cs
  src/InformaticsGateway/Program.cs
  src/InformaticsGateway/Services/Common/IInputDataPluginEngineFactory.cs
  src/InformaticsGateway/Services/Http/DestinationAeTitleController.cs
  src/InformaticsGateway/Services/Http/MonaiAeTitleController.cs
  src/InformaticsGateway/Test/Plugins/TestInputDataPlugins.cs
  src/InformaticsGateway/Test/Plugins/TestOutputDataPlugins.cs
  src/InformaticsGateway/Test/ProgramTest.cs
  src/InformaticsGateway/Test/Services/Common/InputDataPluginEngineFactoryTest.cs
  src/InformaticsGateway/Test/Services/Common/OutputDataPluginEngineFactoryTest.cs
  src/InformaticsGateway/Test/Services/Http/DestinationAeTitleControllerTest.cs
  src/InformaticsGateway/Test/Services/Http/MonaiAeTitleControllerTest.cs
  src/InformaticsGateway/appsettings.json
Labels: feature

#456 Include Plug-ins in Build
  .dockerignore
  src/InformaticsGateway/Monai.Deploy.InformaticsGateway.csproj
Labels: enhancement
